server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

grpc:
  server:
    port: 59091

collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: kafka:29092
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        sensors-events: telemetry.sensors.v1
        hubs-events: telemetry.hubs.v1
